---
- name: Ensure old versions of Docker are not installed
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Update package index
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Get current Architecture in dpkg format
  shell: $(dpkg --print-architecture)
  register: dpkg_architecture

- name: Save current Architecture as variable to be used in the gpg key
  set_fact:
    docker_apt_arch: "{{ dpkg_architecture.stdout }}"

- name: Add Docker GPG key.
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: true