# The username for the ssh connection to the remote server
username: sharknoon
# The apt packages to be installed on the system
packages:
  #- htop

# The apt GPG key to use the docker apt repository over HTTPS
docker_apt_url: https://download.docker.com/linux/{{ ansible_distribution | lower }}
docker_apt_gpg_key: "{{ docker_apt_url }}/gpg"
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_apt_url }} {{ ansible_distribution_release }} stable"